// Database types - Auto-generated from Supabase schema
// To regenerate: npx supabase gen types typescript --project-id YOUR_PROJECT_REF > lib/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string;
          name: string;
          domain: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          domain: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          domain?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      storage_requests: {
        Row: {
          id: string;
          company_id: string;
          user_email: string;
          reference_id: string;
          status: 'DRAFT' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'COMPLETED';
          request_details: Json | null;
          trucking_info: Json | null;
          assigned_location: string | null;
          assigned_rack_ids: string[] | null;
          approval_summary: string | null;
          rejection_reason: string | null;
          archived_at: string | null;
          created_at: string;
          updated_at: string;
          approved_at: string | null;
          approved_by: string | null;
          rejected_at: string | null;
          internal_notes: string | null;
        };
        Insert: {
          id?: string;
          company_id: string;
          user_email: string;
          reference_id: string;
          status?: 'DRAFT' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'COMPLETED';
          request_details?: Json | null;
          trucking_info?: Json | null;
          assigned_location?: string | null;
          assigned_rack_ids?: string[] | null;
          approval_summary?: string | null;
          rejection_reason?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
          approved_at?: string | null;
          approved_by?: string | null;
          rejected_at?: string | null;
          internal_notes?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string;
          user_email?: string;
          reference_id?: string;
          status?: 'DRAFT' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'COMPLETED';
          request_details?: Json | null;
          trucking_info?: Json | null;
          assigned_location?: string | null;
          assigned_rack_ids?: string[] | null;
          approval_summary?: string | null;
          rejection_reason?: string | null;
          archived_at?: string | null;
          created_at?: string;
          updated_at?: string;
          approved_at?: string | null;
          approved_by?: string | null;
          rejected_at?: string | null;
          internal_notes?: string | null;
        };
      };
      inventory: {
        Row: {
          id: string;
          company_id: string;
          request_id: string | null;
          reference_id: string;
          type: 'Drill Pipe' | 'Casing' | 'Tubing' | 'Line Pipe';
          grade: string;
          outer_diameter: number;
          weight: number;
          length: number;
          quantity: number;
          status: 'PENDING_DELIVERY' | 'IN_STORAGE' | 'PICKED_UP' | 'IN_TRANSIT';
          drop_off_timestamp: string | null;
          pickup_timestamp: string | null;
          storage_area_id: string | null;
          assigned_uwi: string | null;
          assigned_well_name: string | null;
          delivery_truck_load_id: string | null;
          pickup_truck_load_id: string | null;
          manifest_item_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          request_id?: string | null;
          reference_id: string;
          type: 'Drill Pipe' | 'Casing' | 'Tubing' | 'Line Pipe';
          grade: string;
          outer_diameter: number;
          weight: number;
          length: number;
          quantity: number;
          status?: 'PENDING_DELIVERY' | 'IN_STORAGE' | 'PICKED_UP' | 'IN_TRANSIT';
          drop_off_timestamp?: string | null;
          pickup_timestamp?: string | null;
          storage_area_id?: string | null;
          assigned_uwi?: string | null;
          assigned_well_name?: string | null;
          delivery_truck_load_id?: string | null;
          pickup_truck_load_id?: string | null;
          manifest_item_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          request_id?: string | null;
          reference_id?: string;
          type?: 'Drill Pipe' | 'Casing' | 'Tubing' | 'Line Pipe';
          grade?: string;
          outer_diameter?: number;
          weight?: number;
          length?: number;
          quantity?: number;
          status?: 'PENDING_DELIVERY' | 'IN_STORAGE' | 'PICKED_UP' | 'IN_TRANSIT';
          drop_off_timestamp?: string | null;
          pickup_timestamp?: string | null;
          storage_area_id?: string | null;
          assigned_uwi?: string | null;
          assigned_well_name?: string | null;
          delivery_truck_load_id?: string | null;
          pickup_truck_load_id?: string | null;
          manifest_item_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      truck_loads: {
        Row: {
          id: string;
          type: 'DELIVERY' | 'PICKUP';
          trucking_company: string;
          driver_name: string;
          driver_phone: string | null;
          arrival_time: string;
          departure_time: string | null;
          joints_count: number;
          storage_area_id: string | null;
          related_request_id: string | null;
          related_pipe_ids: string[] | null;
          assigned_uwi: string | null;
          assigned_well_name: string | null;
          notes: string | null;
          photo_urls: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type: 'DELIVERY' | 'PICKUP';
          trucking_company: string;
          driver_name: string;
          driver_phone?: string | null;
          arrival_time: string;
          departure_time?: string | null;
          joints_count: number;
          storage_area_id?: string | null;
          related_request_id?: string | null;
          related_pipe_ids?: string[] | null;
          assigned_uwi?: string | null;
          assigned_well_name?: string | null;
          notes?: string | null;
          photo_urls?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: 'DELIVERY' | 'PICKUP';
          trucking_company?: string;
          driver_name?: string;
          driver_phone?: string | null;
          arrival_time?: string;
          departure_time?: string | null;
          joints_count?: number;
          storage_area_id?: string | null;
          related_request_id?: string | null;
          related_pipe_ids?: string[] | null;
          assigned_uwi?: string | null;
          assigned_well_name?: string | null;
          notes?: string | null;
          photo_urls?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      shipments: {
        Row: {
          id: string;
          request_id: string;
          company_id: string;
          created_by: string;
          status: 'DRAFT' | 'SCHEDULING' | 'SCHEDULED' | 'IN_TRANSIT' | 'RECEIVED' | 'CANCELLED';
          trucking_method: 'MPS_QUOTE' | 'CUSTOMER_PROVIDED';
          trucking_company: string | null;
          trucking_contact_name: string | null;
          trucking_contact_phone: string | null;
          trucking_contact_email: string | null;
          number_of_trucks: number;
          estimated_joint_count: number | null;
          estimated_total_length_ft: number | null;
          special_instructions: string | null;
          surcharge_applicable: boolean | null;
          surcharge_amount: number | null;
          documents_status: string | null;
          calendar_sync_status: string | null;
          latest_customer_notification_at: string | null;
          created_at: string;
          updated_at: string;
          trucking_load_id: string | null;
        };
        Insert: {
          id?: string;
          request_id: string;
          company_id: string;
          created_by: string;
          status?: 'DRAFT' | 'SCHEDULING' | 'SCHEDULED' | 'IN_TRANSIT' | 'RECEIVED' | 'CANCELLED';
          trucking_method: 'MPS_QUOTE' | 'CUSTOMER_PROVIDED';
          trucking_company?: string | null;
          trucking_contact_name?: string | null;
          trucking_contact_phone?: string | null;
          trucking_contact_email?: string | null;
          number_of_trucks?: number;
          estimated_joint_count?: number | null;
          estimated_total_length_ft?: number | null;
          special_instructions?: string | null;
          surcharge_applicable?: boolean | null;
          surcharge_amount?: number | null;
          documents_status?: string | null;
          calendar_sync_status?: string | null;
          latest_customer_notification_at?: string | null;
          created_at?: string;
          updated_at?: string;
          trucking_load_id?: string | null;
        };
        Update: {
          id?: string;
          request_id?: string;
          company_id?: string;
          created_by?: string;
          status?: 'DRAFT' | 'SCHEDULING' | 'SCHEDULED' | 'IN_TRANSIT' | 'RECEIVED' | 'CANCELLED';
          trucking_method?: 'MPS_QUOTE' | 'CUSTOMER_PROVIDED';
          trucking_company?: string | null;
          trucking_contact_name?: string | null;
          trucking_contact_phone?: string | null;
          trucking_contact_email?: string | null;
          number_of_trucks?: number;
          estimated_joint_count?: number | null;
          estimated_total_length_ft?: number | null;
          special_instructions?: string | null;
          surcharge_applicable?: boolean | null;
          surcharge_amount?: number | null;
          documents_status?: string | null;
          calendar_sync_status?: string | null;
          latest_customer_notification_at?: string | null;
          created_at?: string;
          updated_at?: string;
          trucking_load_id?: string | null;
        };
      };
      shipment_trucks: {
        Row: {
          id: string;
          shipment_id: string;
          sequence_number: number;
          status: 'PENDING' | 'SCHEDULED' | 'INBOUND' | 'ON_SITE' | 'RECEIVED' | 'CANCELLED';
          trucking_company: string | null;
          contact_name: string | null;
          contact_phone: string | null;
          contact_email: string | null;
          scheduled_slot_start: string | null;
          scheduled_slot_end: string | null;
          arrival_time: string | null;
          departure_time: string | null;
          joints_count: number | null;
          total_length_ft: number | null;
          manifest_received: boolean | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          trucking_load_id: string | null;
        };
        Insert: {
          id?: string;
          shipment_id: string;
          sequence_number?: number;
          status?: 'PENDING' | 'SCHEDULED' | 'INBOUND' | 'ON_SITE' | 'RECEIVED' | 'CANCELLED';
          trucking_company?: string | null;
          contact_name?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          scheduled_slot_start?: string | null;
          scheduled_slot_end?: string | null;
          arrival_time?: string | null;
          departure_time?: string | null;
          joints_count?: number | null;
          total_length_ft?: number | null;
          manifest_received?: boolean | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          trucking_load_id?: string | null;
        };
        Update: {
          id?: string;
          shipment_id?: string;
          sequence_number?: number;
          status?: 'PENDING' | 'SCHEDULED' | 'INBOUND' | 'ON_SITE' | 'RECEIVED' | 'CANCELLED';
          trucking_company?: string | null;
          contact_name?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          scheduled_slot_start?: string | null;
          scheduled_slot_end?: string | null;
          arrival_time?: string | null;
          departure_time?: string | null;
          joints_count?: number | null;
          total_length_ft?: number | null;
          manifest_received?: boolean | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          trucking_load_id?: string | null;
        };
      };
      dock_appointments: {
        Row: {
          id: string;
          shipment_id: string;
          truck_id: string | null;
          slot_start: string;
          slot_end: string;
          after_hours: boolean | null;
          surcharge_applied: boolean | null;
          status: 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED';
          calendar_event_id: string | null;
          calendar_sync_status: string | null;
          reminder_24h_sent_at: string | null;
          reminder_1h_sent_at: string | null;
          created_at: string;
          updated_at: string;
          trucking_load_id: string | null;
        };
        Insert: {
          id?: string;
          shipment_id: string;
          truck_id?: string | null;
          slot_start: string;
          slot_end: string;
          after_hours?: boolean | null;
          surcharge_applied?: boolean | null;
          status?: 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED';
          calendar_event_id?: string | null;
          calendar_sync_status?: string | null;
          reminder_24h_sent_at?: string | null;
          reminder_1h_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
          trucking_load_id?: string | null;
        };
        Update: {
          id?: string;
          shipment_id?: string;
          truck_id?: string | null;
          slot_start?: string;
          slot_end?: string;
          after_hours?: boolean | null;
          surcharge_applied?: boolean | null;
          status?: 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED';
          calendar_event_id?: string | null;
          calendar_sync_status?: string | null;
          reminder_24h_sent_at?: string | null;
          reminder_1h_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
          trucking_load_id?: string | null;
        };
      };
      shipment_documents: {
        Row: {
          id: string;
          shipment_id: string;
          truck_id: string | null;
          document_id: string;
          document_type: string;
          status: 'UPLOADED' | 'PROCESSING' | 'PARSED' | 'FAILED' | 'APPROVED';
          parsed_payload: Json | null;
          processing_notes: string | null;
          uploaded_by: string | null;
          created_at: string;
          processed_at: string | null;
          updated_at: string;
          trucking_load_id: string | null;
        };
        Insert: {
          id?: string;
          shipment_id: string;
          truck_id?: string | null;
          document_id: string;
          document_type: string;
          status?: 'UPLOADED' | 'PROCESSING' | 'PARSED' | 'FAILED' | 'APPROVED';
          parsed_payload?: Json | null;
          processing_notes?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
          processed_at?: string | null;
          updated_at?: string;
          trucking_load_id?: string | null;
        };
        Update: {
          id?: string;
          shipment_id?: string;
          truck_id?: string | null;
          document_id?: string;
          document_type?: string;
          status?: 'UPLOADED' | 'PROCESSING' | 'PARSED' | 'FAILED' | 'APPROVED';
          parsed_payload?: Json | null;
          processing_notes?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
          processed_at?: string | null;
          updated_at?: string;
          trucking_load_id?: string | null;
        };
      };
      shipment_items: {
        Row: {
          id: string;
          shipment_id: string;
          truck_id: string | null;
          document_id: string | null;
          inventory_id: string | null;
          manufacturer: string | null;
          heat_number: string | null;
          serial_number: string | null;
          tally_length_ft: number | null;
          quantity: number | null;
          status: 'IN_TRANSIT' | 'IN_STORAGE' | 'MISSING' | 'DAMAGED';
          notes: string | null;
          created_at: string;
          updated_at: string;
          trucking_load_id: string | null;
        };
        Insert: {
          id?: string;
          shipment_id: string;
          truck_id?: string | null;
          document_id?: string | null;
          inventory_id?: string | null;
          manufacturer?: string | null;
          heat_number?: string | null;
          serial_number?: string | null;
          tally_length_ft?: number | null;
          quantity?: number | null;
          status?: 'IN_TRANSIT' | 'IN_STORAGE' | 'MISSING' | 'DAMAGED';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          trucking_load_id?: string | null;
        };
        Update: {
          id?: string;
          shipment_id?: string;
          truck_id?: string | null;
          document_id?: string | null;
          inventory_id?: string | null;
          manufacturer?: string | null;
          heat_number?: string | null;
          serial_number?: string | null;
          tally_length_ft?: number | null;
          quantity?: number | null;
          status?: 'IN_TRANSIT' | 'IN_STORAGE' | 'MISSING' | 'DAMAGED';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          trucking_load_id?: string | null;
        };
      };
      trucking_loads: {
        Row: {
          id: string;
          storage_request_id: string;
          direction: 'INBOUND' | 'OUTBOUND';
          sequence_number: number;
          status: 'NEW' | 'APPROVED' | 'IN_TRANSIT' | 'COMPLETED' | 'CANCELLED';
          scheduled_slot_start: string | null;
          scheduled_slot_end: string | null;
          pickup_location: Json | null;
          delivery_location: Json | null;
          asset_name: string | null;
          wellpad_name: string | null;
          well_name: string | null;
          uwi: string | null;
          trucking_company: string | null;
          contact_company: string | null;
          contact_name: string | null;
          contact_phone: string | null;
          contact_email: string | null;
          driver_name: string | null;
          driver_phone: string | null;
          notes: string | null;
          total_joints_planned: number | null;
          total_length_ft_planned: number | null;
          total_weight_lbs_planned: number | null;
          total_joints_completed: number | null;
          total_length_ft_completed: number | null;
          total_weight_lbs_completed: number | null;
          approved_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          storage_request_id: string;
          direction: 'INBOUND' | 'OUTBOUND';
          sequence_number: number;
          status?: 'NEW' | 'APPROVED' | 'IN_TRANSIT' | 'COMPLETED' | 'CANCELLED';
          scheduled_slot_start?: string | null;
          scheduled_slot_end?: string | null;
          pickup_location?: Json | null;
          delivery_location?: Json | null;
          asset_name?: string | null;
          wellpad_name?: string | null;
          well_name?: string | null;
          uwi?: string | null;
          trucking_company?: string | null;
          contact_company?: string | null;
          contact_name?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          driver_name?: string | null;
          driver_phone?: string | null;
          notes?: string | null;
          total_joints_planned?: number | null;
          total_length_ft_planned?: number | null;
          total_weight_lbs_planned?: number | null;
          total_joints_completed?: number | null;
          total_length_ft_completed?: number | null;
          total_weight_lbs_completed?: number | null;
          approved_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          storage_request_id?: string;
          direction?: 'INBOUND' | 'OUTBOUND';
          sequence_number?: number;
          status?: 'NEW' | 'APPROVED' | 'IN_TRANSIT' | 'COMPLETED' | 'CANCELLED';
          scheduled_slot_start?: string | null;
          scheduled_slot_end?: string | null;
          pickup_location?: Json | null;
          delivery_location?: Json | null;
          asset_name?: string | null;
          wellpad_name?: string | null;
          well_name?: string | null;
          uwi?: string | null;
          trucking_company?: string | null;
          contact_company?: string | null;
          contact_name?: string | null;
          contact_phone?: string | null;
          contact_email?: string | null;
          driver_name?: string | null;
          driver_phone?: string | null;
          notes?: string | null;
          total_joints_planned?: number | null;
          total_length_ft_planned?: number | null;
          total_weight_lbs_planned?: number | null;
          total_joints_completed?: number | null;
          total_length_ft_completed?: number | null;
          total_weight_lbs_completed?: number | null;
          approved_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      trucking_documents: {
        Row: {
          id: string;
          trucking_load_id: string;
          file_name: string;
          storage_path: string;
          document_type: string | null;
          uploaded_by: string | null;
          uploaded_at: string;
        };
        Insert: {
          id?: string;
          trucking_load_id: string;
          file_name: string;
          storage_path: string;
          document_type?: string | null;
          uploaded_by?: string | null;
          uploaded_at?: string;
        };
        Update: {
          id?: string;
          trucking_load_id?: string;
          file_name?: string;
          storage_path?: string;
          document_type?: string | null;
          uploaded_by?: string | null;
          uploaded_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          user_email: string;
          company_id: string;
          reference_id: string | null;
          request_id: string | null;
          messages: Json;
          conversation_type: string | null;
          is_completed: boolean;
          started_at: string;
          last_message_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_email: string;
          company_id: string;
          reference_id?: string | null;
          request_id?: string | null;
          messages?: Json;
          conversation_type?: string | null;
          is_completed?: boolean;
          started_at?: string;
          last_message_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_email?: string;
          company_id?: string;
          reference_id?: string | null;
          request_id?: string | null;
          messages?: Json;
          conversation_type?: string | null;
          is_completed?: boolean;
          started_at?: string;
          last_message_at?: string;
          completed_at?: string | null;
        };
      };
      racks: {
        Row: {
          id: string;
          area_id: string;
          name: string;
          capacity: number;
          capacity_meters: number;
          occupied: number;
          occupied_meters: number;
          allocation_mode: 'LINEAR_CAPACITY' | 'SLOT';
          length_meters: number | null;
          width_meters: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          area_id: string;
          name: string;
          capacity?: number;
          capacity_meters?: number;
          occupied?: number;
          occupied_meters?: number;
          allocation_mode?: 'LINEAR_CAPACITY' | 'SLOT';
          length_meters?: number | null;
          width_meters?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          area_id?: string;
          name?: string;
          capacity?: number;
          capacity_meters?: number;
          occupied?: number;
          occupied_meters?: number;
          allocation_mode?: 'LINEAR_CAPACITY' | 'SLOT';
          length_meters?: number | null;
          width_meters?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      trucking_quotes: {
        Row: {
          id: string;
          request_id: string;
          company_id: string;
          created_by: string;
          quote_number: string;
          origin_address: Json | null;
          destination_address: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          request_id: string;
          company_id: string;
          created_by: string;
          quote_number: string;
          origin_address?: Json | null;
          destination_address?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          request_id?: string;
          company_id?: string;
          created_by?: string;
          quote_number?: string;
          origin_address?: Json | null;
          destination_address?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      documents: {
        Row: {
          id: string;
          company_id: string;
          request_id: string | null;
          file_name: string;
          file_type: string;
          file_size: number;
          storage_path: string;
          extracted_data: Json | null;
          is_processed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          request_id?: string | null;
          file_name: string;
          file_type: string;
          file_size: number;
          storage_path: string;
          extracted_data?: Json | null;
          is_processed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          request_id?: string | null;
          file_name?: string;
          file_type?: string;
          file_size?: number;
          storage_path?: string;
          extracted_data?: Json | null;
          is_processed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_email: string;
          type: 'NEW_REQUEST' | 'DELIVERY_SCHEDULED' | 'PICKUP_SCHEDULED' | 'URGENT_REQUEST' | 'CUSTOMER_MESSAGE';
          title: string;
          message: string;
          read: boolean;
          data: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_email: string;
          type: 'NEW_REQUEST' | 'DELIVERY_SCHEDULED' | 'PICKUP_SCHEDULED' | 'URGENT_REQUEST' | 'CUSTOMER_MESSAGE';
          title: string;
          message: string;
          read?: boolean;
          data?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_email?: string;
          type?: 'NEW_REQUEST' | 'DELIVERY_SCHEDULED' | 'PICKUP_SCHEDULED' | 'URGENT_REQUEST' | 'CUSTOMER_MESSAGE';
          title?: string;
          message?: string;
          read?: boolean;
          data?: Json | null;
          created_at?: string;
        };
      };
      yards: {
        Row: {
          id: string;
          name: string;
          location: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          location?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          location?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      request_status: 'DRAFT' | 'PENDING' | 'APPROVED' | 'REJECTED' | 'COMPLETED';
      pipe_type: 'Drill Pipe' | 'Casing' | 'Tubing' | 'Line Pipe';
      pipe_status: 'PENDING_DELIVERY' | 'IN_STORAGE' | 'PICKED_UP' | 'IN_TRANSIT';
      truck_load_type: 'DELIVERY' | 'PICKUP';
      shipment_status: 'DRAFT' | 'SCHEDULING' | 'SCHEDULED' | 'IN_TRANSIT' | 'RECEIVED' | 'CANCELLED';
      trucking_method: 'MPS_QUOTE' | 'CUSTOMER_PROVIDED';
      shipment_truck_status: 'PENDING' | 'SCHEDULED' | 'INBOUND' | 'ON_SITE' | 'RECEIVED' | 'CANCELLED';
      appointment_status: 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED';
      manifest_document_status: 'UPLOADED' | 'PROCESSING' | 'PARSED' | 'FAILED' | 'APPROVED';
      shipment_item_status: 'IN_TRANSIT' | 'IN_STORAGE' | 'MISSING' | 'DAMAGED';
      notification_type: 'NEW_REQUEST' | 'DELIVERY_SCHEDULED' | 'PICKUP_SCHEDULED' | 'URGENT_REQUEST' | 'CUSTOMER_MESSAGE';
      trucking_load_direction: 'INBOUND' | 'OUTBOUND';
      trucking_load_status: 'NEW' | 'APPROVED' | 'IN_TRANSIT' | 'COMPLETED' | 'CANCELLED';
    };
  };
}
